### ISSUE TITLE
Who is the author of open-methane prior?

### ISSUE THREAD

**Issue by crdanielbusch** [openmethane/openmethane-prior#18]
In the `pyproject.toml` we mention the authors of the repository. There should be at least one author in the form `name` and `email`.

_Originally posted by @lewisjared in https://github.com/openmethane/openmethane-prior/pull/10#discussion_r1616879037_

**Comment by aethr** [comment]
This repo is an original work by Gerard Mason and Peter (see the initial commit here: https://github.com/openmethane/openmethane-prior/commit/63c4f59b3fb21fcb00058087852646d72d74efd3).

If there's room for multiple authors I would definitely mention them both, and definitely add yourself and Jared.

**Comment by aethr** [comment]
Added a suggestion: https://github.com/openmethane/openmethane-prior/pull/10/files/450d0fccecaa096cb2f4d929410e3226a93ccb14#r1618046538

**Comment by crdanielbusch** [comment]
> Added a suggestion: https://github.com/openmethane/openmethane-prior/pull/10/files/450d0fccecaa096cb2f4d929410e3226a93ccb14#r1618046538

Thank you. I will integrate this in the next pull request

**Comment by crdanielbusch** [comment]
Authors are now in `pyproject.toml`
