### ISSUE TITLE
Evaluate impact of updates to CDS

### ISSUE THREAD

**Issue by aethr** [openmethane/openmethane-prior#19]
## The motivation

The team behind Copernicus/CDS has announced they are making substantial changes to the service in an attempt to modernise their infrastructure: 
https://forum.ecmwf.int/t/a-new-cds-soon-to-be-launched-expect-some-disruptions/1607/50

They haven't released (or I couldn't find) any details on how these changes will impacts APIs / downstream consumers. This issue can simply serve as a reminder / TODO to check back periodically to see if changes will be required.

The team has stated:
>  the current Climate and Atmosphere Data Stores will continue to operate until complete shutdown on 1st September 2024.

So we will need to understand before September what, if any, changes will be required on our side.

## The proposed solution

Watch and wait until details have been released about impacts to downstream consumers.

## Additional context

https://forum.ecmwf.int/t/a-new-cds-soon-to-be-launched-expect-some-disruptions/1607

**Comment by mikapfl** [comment]
It seems we need to move to ads-beta because their stable system stops working on 2024-09-26:

```
2024-09-04T13:09:40.725000: 2024-09-04 11:09:40,725 INFO Welcome to the ADS.
2024-09-04T13:09:40.725000: As per our announcements on the Forum, this instance of ADS will be decommissioned on 26 September 2024 and will no longer be accessible from this date onwards.
2024-09-04T13:09:40.725000: Please update your cdsapi package to a version >=0.7.0, create an account on ADS-Beta and update your .cdsapirc file. We strongly recommend users to check our Guidelines at https://confluence.ecmwf.int/x/uINmFw
2024-09-04T13:09:40.725000: 2024-09-04 11:09:40,725 WARNING Move urgently to ads-beta
```

**Comment by aethr** [comment]
The ADS/CDS team now provides a migration guide to the new system: https://confluence.ecmwf.int/display/CKB/Please+read%3A+CDS+and+ADS+migrating+to+new+infrastructure%3A+Common+Data+Store+%28CDS%29+Engine

Steps to migrate openmethane-prior to the new ADS system:
- [x] Register for an ECMWF account (https://www.ecmwf.int/)
- [x] Accept terms for ADS beta with new account: https://ads-beta.atmosphere.copernicus.eu/
- [x] Accept license to use Copernicus products (bottom of the Download page of the dataset we need): https://ads-beta.atmosphere.copernicus.eu/datasets/cams-global-fire-emissions-gfas?tab=download
- [x] Accept terms for CDS beta with new account: https://cds-beta.climate.copernicus.eu/
- [ ] Update credentials used in GHA
- [ ] Update documentation to guide users to the new ADS account process
