### ISSUE TITLE
`omInputs` exports can't be updated after generating domain file

### ISSUE THREAD

**Issue by aethr** [openmethane/openmethane-prior#23]
## The motivation

The test in #11 can't generate a domain file on the fly due to how `omInputs` exports are constructed. In a nutshell:
- when `omInputs` is imported, it creates vars `domainXr` and `domainProj` in the root scope, with value `None`
- if a domain file is present, it gets read and values for `domainXr` and `domainProj` are updated
- any modules that import `omInputs` get domain vars that either have `None` or values depending on the state of the filesystem at import time

In the case of `omDomainJSON.py`, it uses `domainXr` and `domainProj` by simply importing them. If the domain file isn't there, there's nothing it can do other than raise an error. However, to write a test for `omDomainJSON.py` we need to have a domain file to test. With the current structure, it's not even possible to run `omCreateDomainInfo.py` within the test, because doing so will not update the exports from `omInputs`.

## The proposed solution

Although it seems wasteful building the domain file as part of the tests, the JSON export has to work with the current format of the domain file. Ideally the code that constructs the real domain should be usable to create a test domain (even if the test domain is the real domain for right now).

**Comment by lewisjared** [comment]
This has been resolved and the test is now running in main.

The fix was to remove the use of global state everywhere.
