### ISSUE TITLE
problem importing openmethane_prior

### ISSUE THREAD

**Issue by prayner** [openmethane/openmethane-prior#27]
## The problem
I'd like to import the openmethane_prior package for testing.
It's failing, probably due to me misunderstanding the steps *before*
running ipython.
## Definition of$ "done"
- import openmethane_prior returns successfully
## Additional context
Here's what I tried:
python -m venv venvdir
(3.9) > source venvdir/bin/activate
(venvdir) (3.9) > pwd
/home/unimelb.edu.au/prayner/work/openmethane-beta/prior
(venvdir) (3.9) > pip install -r requirements.txt
deleted long output
(venvdir) (3.9) > pip install -r requirements-dev.txt
deleted shorter output
(venvdir) (3.9) > cd src
(venvdir) (3.9) > ipython
Activating auto-logging. Current session state plus future input saved.
Filename       : /home/unimelb.edu.au/prayner/ipython-log.py
Mode           : append
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import openmethane_prior
---------------------------------------------------------------------------
PackageNotFoundError                      Traceback (most recent call last)
Cell In[1], line 1
----> 1 import openmethane_prior

File ~/work/openmethane-beta/prior/src/openmethane_prior/__init__.py:6
      1 """
      2 Open methane prior.
      3 """
      4 import importlib.metadata
----> 6 __version__ = importlib.metadata.version("openmethane_prior")

File ~/.conda/envs/prayner/envs/3.9/lib/python3.9/importlib/metadata.py:569, in version(distribution_name)
    562 def version(distribution_name):
    563     """Get the version string for the named package.
    564 
    565     :param distribution_name: The name of the distribution package to query.
    566     :return: The version string for the package as defined in the package's
    567         "Version" metadata key.
    568     """
--> 569     return distribution(distribution_name).version

File ~/.conda/envs/prayner/envs/3.9/lib/python3.9/importlib/metadata.py:542, in distribution(distribution_name)
    536 def distribution(distribution_name):
    537     """Get the ``Distribution`` instance for the named package.
    538 
    539     :param distribution_name: The name of the distribution package as a string.
    540     :return: A ``Distribution`` instance (or subclass thereof).
    541     """
--> 542     return Distribution.from_name(distribution_name)

File ~/.conda/envs/prayner/envs/3.9/lib/python3.9/importlib/metadata.py:196, in Distribution.from_name(cls, name)
    194         return dist
    195 else:
--> 196     raise PackageNotFoundError(name)

PackageNotFoundError: openmethane_prior

In [2]: exit

@openmethane/climate-resource, could you take a look at this, I can't
assign to a group

**Comment by lewisjared** [comment]
With moving the package to src you need to reinstall it.

The best way forward is to install poetry and then run make install.

The hack fix would be to run pip install -e .
