### ISSUE TITLE
Possible location / projection issue with prior layers

### ISSUE THREAD

**Issue by aethr** [openmethane/openmethane-prior#31]
## Describe the bug

I've recently been able to ingest the prior into the openmethane-fe map view using the following process:
- update `scripts/omGeoJSON.py` to work with new package name
- export values from `outputs/out-om-domain.nc` variable `OCH4_TOTAL` in the JSON output
- ingest `OCH4_TOTAL` values into local database against the grid cell id `10-{x}-{y}`
- display the `OCH4_TOTAL` value as a colour overlay over each grid cell

The result looks like this:
![image](https://github.com/openmethane/openmethane-prior/assets/5225855/82c09cd2-225b-4bab-a6ab-f9e2aa91eda8)

 - cells with a `0.0` value for `OCH4_TOTAL` have no overlay color
 - cells with a non-zero value use a red/purple color stop to display the scale of the emissions

Zooming in on an area in NSW we can see some high emission cells (and map label tells us we're looking at Drayton Mine):
![image](https://github.com/openmethane/openmethane-prior/assets/5225855/e40e9051-d921-48a6-a3c3-a74481d6eaaf)

## Failing Test

On the west coast of Australia, there appears to be low levels of emission up to 70km offshore, and some high emissions in the sea, which are shaped like the contour of the coast:
![image](https://github.com/openmethane/openmethane-prior/assets/5225855/9742ec77-07ad-4fd7-94be-bc446568baf9)

This may indicate that one or more of the layers of the prior are using inaccurate projection or coordinates and are displacing the results geographically.

Of particular note are:
- cell `10-33-285` (long: 114.45702362060547, lat: -19.80621337890625)
  - may correlate to the LNG plant on Barrow Island
  - real grid cell is `10-45-276` (long: 115.48302459716797, lat: -20.78216552734375)
- cell `10-41-284` (long: 115.21048736572266, lat: -20.005661010742188)
  - may correlate to the Sino Iron Project
  - real grid cell is likely `10-52-274` (long: 116.13399505615234, lat: -21.05402183532715)

## Expected behavior

I would expect to see these emission hotspots over land.

## Screenshots

See above.

## System

 - OS: [e.g. Windows, Linux, macOS]
 - Python version [e.g. Python 3.11]
 - Please also upload your `poetry.lock` file (first run `poetry lock` to make sure the lock file is up-to-date)

## Additional context

May be related to:
- #17 
- #24

**Comment by aethr** [comment]
@lewisjared discovered that there is some naive projection code in the fugitive emissions layer that is very likely the cause of this discrepancy:

https://github.com/openmethane/openmethane-prior/blob/af75230e587941002f655fbe4139fbeeb8355463/src/openmethane_prior/layers/omFugitiveEmis.py#L78-L93

I've confirmed via testing in the front-end that if only `OCH4_FUGITIVE` emission is visualised, it results in these offshore emissions off the west coast.

**Comment by prayner** [comment]
Where are the west coast emissions? Climate Trace which drives the
fugitive layer does have offshore emissions from gas extraction, there
were also some in Bass Strait.

Nasimeh had noted problems with the industrial sector as well.

**Comment by aethr** [comment]
@prayner that is very interesting, and sure enough the Climate Trace map has these spots: 
![image](https://github.com/openmethane/openmethane-prior/assets/5225855/07a2a843-320a-4f4e-bba1-65a68b5297cb)

Some quick googling reveals these are offshore oil+gas fields.

**Comment by aethr** [comment]
It looks as though these spots are expected so I'm closing this issue.
