### ISSUE TITLE
Climate Trace data not available

### ISSUE THREAD

**Issue by lewisjared** [openmethane/openmethane-prior#4]
When running' omDownloadInputs.py, ' the climate trace data cannot be downloaded successfully. The downloaded file is actually a "Not Found" HTML page.

This bad file later causes `omFugitiveEmis.py` to fail.

**Comment by lewisjared** [comment]
@crdanielbusch this might be the reason for the failure.

**Comment by lewisjared** [comment]
@prayner @aethr are the climate trace data needed or can they be safely ignored? If not are there download scripts for the climate trace data

**Comment by aethr** [comment]
Report from @crdanielbusch:

> this link works for me: https://prior.openmethane.org/ch4-electricity.csv
> But this one doesn't: https://prior.openmethane.org/coal-mining_emissions-sources.csv

**Comment by crdanielbusch** [comment]
> @crdanielbusch this might be the reason for the failure.

I think it's the same problem. The two files I cannot fetch are the ones from the climate trace data set.

**Comment by aethr** [comment]
I've uploaded the files to the `prior.openmethane.org` R2 bucket:
> https://prior.openmethane.org/coal-mining_emissions-sources.csv
> https://prior.openmethane.org/oil-and-gas-production-and-transport_emissions-sources.csv

Fetching these looks like it should work now:
```sh
$ curl -O -sS -v https://prior.openmethane.org/coal-mining_emissions-sources.csv
...
< HTTP/2 200
...

$ curl -O -sS -v https://prior.openmethane.org/oil-and-gas-production-and-transport_emissions-sources.csv
...
< HTTP/2 200
...
```
